#!/bin/bash
################################################################################
# Make sure this script DOES NOT run on PROD Mongo
PROD_MONGO_INST_ID="i-d7a8ff73"
STG_MONGO_INST_ID="i-83481f27"

echo "Identifying current machine..."
SELF_INST_ID="`wget -q -O - http://instance-data/latest/meta-data/instance-id || echo \"not-ec2\"`"

if [ $SELF_INST_ID == $PROD_MONGO_INST_ID ]
then
	echo "FATAL: This script CANNOT run on PROD-MONGO1!"
	exit
fi

################################################################################
