#!/bin/bash
echo "Updating doorkeeper for localhost authorization."

PROD_MONGO_INST_ID="i-d7a8ff73"
STG_MONGO_INST_ID="i-83481f27"

echo "Identifying current machine..."
SELF_INST_ID="`wget -q -O - http://instance-data/latest/meta-data/instance-id || echo \"not-ec2\"`"

if [ $SELF_INST_ID == $PROD_MONGO_INST_ID ]
then
	echo "FATAL: This script CANNOT run on PROD-MONGO1!"
	exit
fi

if [ $SELF_INST_ID != $STG_MONGO_INST_ID ]
then
	mv avanti_cms_development avanti-cms_production
	mv avanti_lms_development avanti-lms_production
	mv avanti_service_development avanti-service_production
	mv avanti_test_development avanti-test_production

	mongo avanti_service_development --eval 'db.oauth_applications.update({ "name" : "avanti_cms" }, { $set: { "redirect_uri": "http://localhost:3001/auth/avanti/callback"}})'
	mongo avanti_service_development --eval 'db.oauth_applications.update({ "name" : "avanti_lms" }, { $set: { "redirect_uri": "http://localhost:3002/auth/avanti/callback"}})'
	mongo avanti_service_development --eval 'db.oauth_applications.update({ "name" : "avanti_test" }, { $set: { "redirect_uri": "http://localhost:3003/auth/avanti/callback"}})'
else
	mongo avanti-service_production --eval 'db.oauth_applications.update({ "name" : "avanti_cms" }, { $set: { "redirect_uri": "http://cms.staging.peerlearning.com/auth/avanti/callback"}})'
	mongo avanti-service_production --eval 'db.oauth_applications.update({ "name" : "avanti_lms" }, { $set: { "redirect_uri": "http://lms.staging.peerlearning.com/auth/avanti/callback"}})'
	mongo avanti-service_production --eval 'db.oauth_applications.update({ "name" : "avanti_test" }, { $set: { "redirect_uri": "http://test.staging.peerlearning.com/auth/avanti/callback"}})'
fi
