#!/bin/bash
# Restores the local data base without calling git pull

################################################################################
# Make sure this script DOES NOT run on PROD Mongo
PROD_MONGO_INST_ID="i-d7a8ff73"
STG_MONGO_INST_ID="i-83481f27"

echo "Identifying current machine..."
SELF_INST_ID="`wget -q -O - http://instance-data/latest/meta-data/instance-id || echo \"not-ec2\"`"

if [ $SELF_INST_ID == $PROD_MONGO_INST_ID ]
then
	echo "FATAL: This script CANNOT run on PROD-MONGO1!"
	exit
fi
################################################################################


echo "Restoring DB..."

mv .git dot_git

if [ $SELF_INST_ID != $STG_MONGO_INST_ID ]
then

	echo "Unzipping latest DB..."
	rm -rf avanti-*_production && \
	untar_out=$(tar -xvf latest_dump.tar.gz)

	echo "Renaming DBs for restore..."
	mv avanti-cms_production avanti_cms_development
	mv avanti-lms_production avanti_lms_development
	mv avanti-service_production avanti_service_development
	mv avanti-test_production avanti_test_development
fi

echo "Starting mongorestore..."
echo "mongorestore --host 127.0.0.1 --drop --port 27017 ./"
restore_our=$(mongorestore --host 127.0.0.1 --drop --port 27017 ./)

echo "Finishing up..."
mv dot_git .git

./reset_doorkeeper

echo "                              Finished!"
echo "--------------------------------------------------------------------------------"
echo "                    Happy Happy Joy Joy :) :D :*"
echo "--------------------------------------------------------------------------------"
